CREATE TABLE collection (
  id SERIAL PRIMARY KEY,
  is_stored BOOLEAN NOT NULL DEFAULT FALSE,
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  amount_left INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  coffee_id SERIAL NOT NULL REFERENCES coffees (id)
);
